spring:
  datasource:
    url: jdbc:postgresql://dpg-cu5vfll6l47c73btda5g-a.oregon-postgres.render.com/beautytouch
    username: beautytouch_user
    password: DeN9EehCSAyx0MEl0ve8FGpZ5tBwA0u1

  jpa:
    hibernate:
      ddl-auto: none # Tùy chọn tốt cho môi trường phát triển
    show-sql: true # Hiển thị câu lệnh SQL trong logs
    properties:
      hibernate:
        format_sql: true # Định dạng SQL để dễ đọc

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  web:
    resources:
      static-locations: classpath:/static/

  mail:
    host: smtp.gmail.com
    port: 587
    username: tinhtqqe170178@fpt.edu.vn
    password: jhep futm jgxj atsu
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

logging:
  level:
    org.springframework.security: DEBUG
    com.beautytouch: DEBUG
  file:
    name: app.log

cloudinary:
  cloud:
    name: 'ddpdyo3w8'
  api:
    key: 443987573159755
    secret: gspgdRsnmPl0uxg5XCiqa0-H-Ig
server:
  port: 8080