spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/beautytouch?useSSL=false&serverTimezone=UTC"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
